name: Main

on:
  push:
    branches: [main]

permissions:
  actions: write
  packages: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  linting:
    name: Linting
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Hadolint
        uses: hadolint/hadolint-action@v3.1.0

  build:
    uses: Ilyes512/github-actions/.github/workflows/build.yml@1.0.3
    needs: linting
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - os: ubuntu-24.04
            platform: linux/amd64
          - os: ubuntu-24.04-arm
            platform: linux/arm64
    with:
      runs-on: ${{ matrix.runs-on.os }}
      platform: ${{ matrix.runs-on.platform }}
      image-name: ghcr.io/${{ github.repository }}

  merge:
    uses: Ilyes512/github-actions/.github/workflows/merge.yml@1.0.3
    needs: build
    with:
      runs-on: ubuntu-24.04
      image-name: ghcr.io/${{ github.repository }}
